-- 07_merge_kline_updates.sql
--
-- processed_klines 에 kline update를 MERGE INTO로 반영한다.
-- PRD §10.4, §12.2, §11 (COW) 참조.
--
-- Key: (symbol, interval, open_time)
--
-- 보류 / 미정 (decisions.md D6):
--   1. micro-batch 안에서 같은 키의 중복 — 어떤 컬럼 기준으로 dedup할지 결정 필요.
--      kline은 같은 (symbol, interval, open_time) 으로 수십 건이 한 batch에 들어올
--      수 있으므로 row_number() OVER (PARTITION BY ... ORDER BY ... DESC) 방식을
--      쓸 가능성이 크다. 정확한 ORDER BY 컬럼은 Phase 2에서 결정.
--   2. late event 방어 — source.updated_at < target.updated_at 인 경우 무시할지,
--      kline의 경우 close_time / event_time 중 무엇을 단조성 기준으로 쓸지 결정 필요.
--
-- 본 파일은 위 두 결정이 끝난 뒤 활성화한다.

-- TODO Phase 2
-- WITH staging AS (
--     SELECT * FROM (
--         SELECT *,
--                row_number() OVER (
--                    PARTITION BY symbol, `interval`, open_time
--                    ORDER BY <tiebreaker> DESC
--                ) AS rn
--         FROM tmp_klines_batch
--     )
--     WHERE rn = 1
-- )
-- MERGE INTO <catalog>.processed.processed_klines t
-- USING staging s
--   ON  t.symbol     = s.symbol
--   AND t.`interval` = s.`interval`
--   AND t.open_time  = s.open_time
-- WHEN MATCHED /* AND s.updated_at >= t.updated_at */ THEN UPDATE SET *
-- WHEN NOT MATCHED THEN INSERT *;
