-- 08_merge_order_status_updates.sql
--
-- processed_orders 에 주문 상태 변화를 MERGE INTO로 반영한다.
-- PRD §10.5, §12.1, §11 (COW) 참조.
--
-- Key: order_id
-- 상태 전이:
--   NEW → PARTIALLY_FILLED → FILLED
--   NEW → CANCELED
--
-- 보류 / 미정 (decisions.md D6):
--   1. micro-batch 안의 같은 order_id 중복 dedup — kline과 동일 패턴.
--   2. late event 방어 — s.updated_at < t.updated_at 인 경우 무시.
--   3. 상태 역행 방지 — FILLED 상태에서 PARTIALLY_FILLED 이벤트가 늦게 도착하는
--      경우의 처리 정책. Phase 2에서 결정.
--
-- 본 파일은 위 결정이 끝난 뒤 활성화한다.

-- TODO Phase 2
-- WITH staging AS (
--     SELECT * FROM (
--         SELECT *,
--                row_number() OVER (
--                    PARTITION BY order_id
--                    ORDER BY <tiebreaker> DESC
--                ) AS rn
--         FROM tmp_orders_batch
--     )
--     WHERE rn = 1
-- )
-- MERGE INTO <catalog>.processed.processed_orders t
-- USING staging s
--   ON t.order_id = s.order_id
-- WHEN MATCHED /* AND s.updated_at >= t.updated_at */ THEN UPDATE SET *
-- WHEN NOT MATCHED THEN INSERT *;
