-- 01_create_namespaces.sql
--
-- 네임스페이스(= Glue database) 정책.
--
-- 결정(decisions.md D8): 단일 database `binance_lakehouse` 안에 모든 테이블을 두고,
-- 레이어는 테이블 이름 prefix로 구분한다 (raw_/processed_/staging_/serving_/ops_).
-- Glue database는 콘솔/IaC로 생성하므로 별도 CREATE NAMESPACE SQL은 두지 않는다.
--
-- 논리적 zone ↔ 테이블:
--   raw       : raw_trades, raw_klines, raw_orders                 (plain Parquet, Iceberg 아님)
--   processed : processed_trades, processed_klines, processed_orders
--   staging   : staging_klines, staging_orders
--   serving   : market_hourly_summary, order_execution_summary
--   ops       : data_quality_summary, pipeline_run_summary, table_health_summary, quality_events
--
-- 로컬 벤치(hadoop catalog)는 `local.bench` 네임스페이스를 코드에서 생성한다
-- (src/bench/lag_stream.py, src/quality/quality_scan.py).
